name: todo_app
description: "A simple list app to manage your tasks and notes."
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.10.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_quill: ^11.4.1
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  uuid: ^4.0.0
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  loading_animation_widget: ^1.3.0
  table_calendar: ^3.2.0
  flutter_colorpicker: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"

flutter_icons:
  - image_path: "assets/icon/app_icon.png"
    android: true
    ios: true
    web: true
    
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.png
